name: tensorflow_gpu
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py37_0
  - astor=0.8.0=py37_0
  - astroid=2.3.3=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - colorama=0.4.3=py_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cycler=0.10.0=py_2
  - freetype=2.10.0=h563cfd7_1
  - gast=0.2.2=py37_0
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - intel-openmp=2020.0=166
  - isort=4.3.21=py37_0
  - joblib=0.14.1=py_0
  - jpeg=9c=hfa6e2cd_1001
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he980bc4_0
  - lazy-object-proxy=1.4.3=py37he774522_0
  - libclang=9.0.1=default_hf44288c_0
  - libpng=1.6.37=h7602738_0
  - libprotobuf=3.11.2=h7bd577a_0
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h2981e6d_0
  - mccabe=0.6.1=py37_1
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - numpy=1.18.1=py37h93ca92e_0
  - numpy-base=1.18.1=py37hc3f5095_1
  - openssl=1.1.1d=he774522_4
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.1=py37h47e9c7a_0
  - pip=20.0.2=py37_1
  - protobuf=3.11.2=py37h33f27b4_0
  - pylint=2.4.4=py37_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.12.3=py37h6538335_1
  - pyreadline=2.1=py37_1
  - python=3.7.6=h60c2a47_2
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.3=py37he774522_0
  - qt=5.12.5=h7ef1ec2_0
  - rope=0.16.0=py_0
  - scikit-learn=0.22.1=py37h6288b17_0
  - scipy=1.4.1=py37h9439919_0
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=he774522_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=1.15.0=gpu_py37hc3743a6_0
  - tensorflow-base=1.15.0=gpu_py37h1afeea4_0
  - tensorflow-estimator=1.15.1=pyh2649769_0
  - tensorflow-gpu=1.15.0=h0d30ee6_0
  - termcolor=1.1.0=py37_1
  - tornado=6.0.3=py37hfa6e2cd_3
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
  - wrapt=1.11.2=py37he774522_0
  - yaml=0.1.7=vc14h4cb57cf_1
  - zlib=1.2.11=h62dcd97_3
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
prefix: C:\Users\Norbi\Anaconda3\envs\tensorflow_gpu

